# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Dell Inc, or its subsidiaries.

version: "3.7"

services:

  alertservice:
    image: "alertservice:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9001:9001"
    privileged: true
    networks:
      - sfss

  app-rest:
    image: "app-rest:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9002:9002"
    privileged: true
    networks:
      - sfss

  cdcproxy:
    image: "cdcproxy:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9003:9003"
    privileged: true
    networks:
      - sfss

  centralnz:
    image: "centralnz:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9004:9004"
    privileged: true
    networks:
      - sfss

  discoverymdns:
    image: "discoverymdns:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9005:9005"
    privileged: true
    networks:
      - sfss

  fabricmanager:
    image: "fabricmanager:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9006:9006"
    privileged: true
    networks:
      - sfss

  lcm:
    image: "lcm:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9007:9007"
    privileged: true
    networks:
      - sfss

  license:
    image: "license:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9008:9008"
    privileged: true
    networks:
      - sfss

  monitor:
    image: "monitor:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9009:9009"
    privileged: true
    networks:
      - sfss

  stfs-mgmt:
    image: "stfs-mgmt:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9010:9010"
    environment:
      DEPLOYMENT_MODEL: EMBEDDED
    privileged: true
    networks:
      - sfss

  stfs-redis:
    image: "stfs-redis:1.1.0.0038"
    volumes:
      - /proc:/proc
      - redis_data:/data
    ports:
      - "9011:9011"
    privileged: true
    networks:
      - sfss

  stfs-syslog-ng:
    image: "stfs-syslog-ng:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9012:9012"
    privileged: true
    networks:
      - sfss

  rest:
    image: "rest:1.1.0.0038"
    volumes:
      - /proc:/proc
    ports:
      - "9013:9013"
    privileged: true
    networks:
      - sfss

networks:
  sfss:

volumes:
    redis_data: