name: Linters

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest --ignore=minutes --disable=MD013 "**/*.md"

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azohra/shell-linter@v0.6.0

  powershell-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@v2.4.0

  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pyflakes
        uses: reviewdog/action-pyflakes@v1.6.0
        with:
          github_token: ${{ secrets.github_token }}
