name: SFSS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  sfss-debian:
    runs-on: ubuntu-latest
    steps:
    - name: Install SFSS deb
      run: |
        set -x
        wget https://linux.dell.com/files/SANdbox/1.1.0/sfss-1.1.0.0038.deb.zip
        unzip sfss-1.1.0.0038.deb.zip
        sudo dpkg -i sfss-1.1.0.0038.deb
    - name: Test SFSS deb
      run: echo "TBD"

  sfss-compose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@95cb08cb2672c73d4ffd2f422e6d11953d2a9c70

    - name: Download docker images until published
      run: |
        set -x
        wget https://linux.dell.com/files/SANdbox/1.1.0/sfss-1.1.0.0038.deb.zip
        unzip sfss-1.1.0.0038.deb.zip
        ar xv sfss-1.1.0.0038.deb
        tar -xvf data.tar.xz
        cd ./pkgs/sfss/images/sfss-1.1.0.0038
        for i in $( ls ); do docker load < $i; done

    - name: Start containers
      run: docker-compose up -d
      working-directory: "Centralized Discovery Controller (CDC)/SFSS"

    - name: Logs
      if: always() # TODO: replace with failure going forward
      run: docker-compose logs
      working-directory: "Centralized Discovery Controller (CDC)/SFSS"

    - name: Stop containers
      if: always()
      run: docker-compose down
      working-directory: "Centralized Discovery Controller (CDC)/SFSS"
