name: SFSS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  sfss-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@d5234d6605774d496731c394511848830d37a200

    - name: Start containers
      run: docker-compose up -d || true
      working-directory: "Centralized Discovery Controller (CDC)/SFSS"

    - name: Logs
      if: always() # TODO: replace with failure going forward
      run: docker-compose logs
      working-directory: "Centralized Discovery Controller (CDC)/SFSS"

    - name: Stop containers
      if: always()
      run: docker-compose down
      working-directory: "Centralized Discovery Controller (CDC)/SFSS"
